@echo off
mkdir ..\target
echo main osztalyok forditasa...
javac -cp ..\target -d ..\target -sourcepath ..\src ..\src\main\*.java
echo gameobjects osztalyok forditasa...
javac -cp ..\target -d ..\target -sourcepath ..\src ..\src\gameobjects\*.java
echo utils osztalyok forditasa...
javac -cp ..\target -d ..\target -sourcepath ..\src ..\src\utils\*.java
