@echo off
mkdir ..\target
echo controller osztalyok forditasa...
javac -cp ..\target -d ..\target -sourcepath ..\src ..\src\controller\*.java
echo model osztalyok forditasa...
javac -cp ..\target -d ..\target -sourcepath ..\src ..\src\model\*.java
echo utils osztalyok forditasa...
javac -cp ..\target -d ..\target -sourcepath ..\src ..\src\utils\*.java
